- name: Check if content-view {{ name }} exists already
  command: >
    hammer --output json -u "{{ username }}" -p "{{ password}}"
    content-view info
    --organization "{{ organization }}"
    --name "{{ name }}"
  register: cv_output
  ignore_errors: True
  changed_when: False
  failed_when: cv_output|failed and not 'not found' in cv_output.stderr

- name: Create content-view {{ name }}
  command: >
    hammer --output json -u "{{ username }}" -p "{{ password }}"
    content-view create
    --organization "{{ organization }}"
    --name "{{ name }}"
  when: cv_output|failed and 'not found' in cv_output.stderr

