---

- name: Install dependences
  yum: name={{ item }} state=present
  with_items:
      - '{{ "rhevm" if ansible_distribution == "RedHat" else "ovirt-engine" }}'
      - glusterfs-fuse
      - python-enum34
  async: 3600
  poll: 5
  tags:
    - packages

- name: Stop and disable NetworkManager
  service:
      name: NetworkManager
      enabled: no
      state: stopped
  tags:
    - setup

- name: restart network service to pick up correct network scripts
  service:
    name: network
    enabled: yes
    state: restarted
  tags:
    - setup

- name: create config directory
  file:
      path: '{{ config_dir }}'
      state: directory
      mode: 0700
  tags:
    - setup

- name: Get the answer file over there
  template:
      src: answers.j2
      dest: '{{ config_dir }}/answers'
      mode: 0600
  tags:
    - setup

- name: check if the setup has already run
  command: systemctl status ovirt-engine
  register: installed
  changed_when: false
  failed_when: false
  ignore_errors: yes

- name: Execute engine setup
  shell: |
    engine-setup --offline --config-append={{ config_dir }}/answers
  async: 12000
  poll: 5
  when: '{{ installed.rc > 0 }}'
  tags:
    - install
