---

# self-hosted-answers
engine_fqdn: ovirt-engine.example.com
engine_vm_ram: 4096
engine_vm_cpus: 2
engine_setup_timeout: 3600
gateway: '192.168.1.1'
dc_name: Default
cluster_name: Default
storage_datacenter_name: hosted_storage
storage_type: nfs
storage_domain_type: "{{ 'nfs3' if storage_type == 'nfs' else storage_type }}"
hosted_storage_name: my_hosted_storage
hosted_storage_addrees: localhost
hosted_storage_path: /path/to/storage
mac_address: '11:22:33:44:55:66'
engine_mac_address: '00:11:22:33:44:55'
cpu_model: model_Nehalem
root_password: changeme
admin_password: changeme
config_dir: /etc/ansible-ovirt
host_id: 1
host_name: hosted_engine_{{ host_id }}

# user-data
engine_db_host: localhost
engine_db_user: root
engine_db_port: 5432
engine_db_password: dbpassword
engine_organization: localdomain
engine_application_mode: virt
ssh_authorized_key: null
