- name: Check if product {{ name }} exists already
  command: >
    hammer --output json -u "{{ username }}" -p "{{ password }}"
    product info --name "{{ name }}" --organization "{{ organization }}"
  register: product_output
  ignore_errors: True
  changed_when: False
  failed_when: product_output|failed and not 'not found' in product_output.stderr

- name: Create product {{ name }}
  command: >
    hammer --output json -u "{{ username }}" -p "{{ password }}"
    product create --name "{{ name }}" --organization "{{ organization }}"
  when: product_output|failed and 'not found' in product_output.stderr