---

- name: ensure the script directory exists
  file:
    path: '{{ config_dir }}/scripts'
    state: directory
    recurse: yes
    mode: 0700
  tags:
    - config

- name: copy storage setup script
  copy:
    src: files/storage_setup
    dest: '{{ config_dir }}/scripts/storage_setup'
    mode: 0700
  tags:
    - config

- name: Set up data domain
  command: >
    {{ config_dir }}/scripts/storage_setup  --url='https://{{ engine_fqdn }}/ovirt-engine/api'
                                            --username='{{ engine_username }}'
                                            --password='{{ admin_password }}'
                                            --datacenter='{{ dc_name }}'
                                            --storage-name='{{ data_storage_name }}'
                                            --storage-path='{{ data_storage_path }}'
                                            --storage-address='{{ data_storage_address }}'
                                            --storage-type='{{ storage_type }}'
                                            --domain-type='data'
  register: data_domain_output
  retries: 5
  until: data_domain_output|succeeded
  delay: 30
  tags:
    - config

- name: Set up export domain
  command: >
    {{ config_dir }}/scripts/storage_setup  --url='https://{{ engine_fqdn }}/ovirt-engine/api'
                                            --username='{{ engine_username }}'
                                            --password='{{ admin_password }}'
                                            --datacenter='{{ dc_name }}'
                                            --storage-name='{{ export_storage_name }}'
                                            --storage-path='{{ export_storage_path }}'
                                            --storage-address='{{ export_storage_address }}'
                                            --storage-type='{{ storage_type }}'
                                            --domain-type='export'
  when: create_export_domain
  register: export_domain_output
  retries: 5
  delay: 30
  until: export_domain_output|succeeded
  tags:
    - config
